services:
  egg:
    image: egg
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OWNER_PHONE_NUMBER=${OWNER_PHONE_NUMBER}
