services:
  egg:
    image: egg
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    environment:
      - SIGNAL_API_URL=${SIGNAL_API_URL}
      - SIGNAL_NUMBER=${SIGNAL_NUMBER}
      - OWNER_PHONE_NUMBER=${OWNER_PHONE_NUMBER}
