apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haileys-garden.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haileys-garden.labels" . | nindent 4 }}
type: Opaque
stringData:
  SIGNAL_NUMBER: {{ .Values.config.signalNumber | quote }}
  OWNER_PHONE_NUMBER: {{ .Values.config.ownerPhoneNumber | quote }}
