{{- if .Values.trufflehog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haileys-garden.fullname" . }}-trufflehog-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haileys-garden.labels" . | nindent 4 }}
    app.kubernetes.io/component: trufflehog
type: Opaque
stringData:
  database-password: {{ .Values.postgresql.auth.password | quote }}
  {{- if .Values.trufflehog.config.github.enabled }}
  github-token: "ghp_EXAMPLE_TOKEN_REPLACE_ME"
  {{- end }}
  {{- if .Values.trufflehog.config.slack.enabled }}
  slack-webhook: "https://hooks.slack.com/services/EXAMPLE/REPLACE/ME"
  {{- end }}
{{- end }}
