{{- if and .Values.trufflehog.enabled .Values.trufflehog.config.s3.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "haileys-garden.fullname" . }}-trufflehog-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haileys-garden.labels" . | nindent 4 }}
    app.kubernetes.io/component: trufflehog
  {{- with .Values.trufflehog.config.s3.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
