{{- if and .Values.trufflehog.enabled .Values.trufflehog.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "haileys-garden.fullname" . }}-trufflehog
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haileys-garden.labels" . | nindent 4 }}
    app.kubernetes.io/component: trufflehog
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.trufflehog.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "haileys-garden.fullname" . }}-trufflehog
            port:
              number: {{ .Values.trufflehog.service.port }}
{{- end }}
