// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Egg struct {
	ID                string  `json:"id"`
	Type              string  `json:"type"`
	Price             float64 `json:"price"`
	QuantityAvailable int     `json:"quantityAvailable"`
	Description       *string `json:"description,omitempty"`
}

type Mutation struct {
}

type PurchaseResult struct {
	Success           bool   `json:"success"`
	Message           string `json:"message"`
	RemainingQuantity int    `json:"remainingQuantity"`
}

type Query struct {
}
